require 'set'
require 'kmeans/pair'
require 'kmeans/pearson'
require 'kmeans/cluster'
require 'play_it/clusterer'
require 'play_it/config'
require 'play_it/music'
require 'play_it/library'
require 'play_it/logger'

require_relative './../config/config.rb'
